### ISSUE TITLE
Cmake failed to compile

### ISSUE THREAD

**Issue by mrsabhar** [01org/clDNN#1]
![image](https://cloud.githubusercontent.com/assets/7329284/26339711/b7a3ad5e-3f3e-11e7-8a9b-902d1c7dca1b.png)

Getting error when I do "make" - 
 cmake -E make_directory build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make

Any help? I'm running on Ubunutu 16.04

In file included from /home/ae/Documents/clDNN/src/fully_connected.cpp:18:0:
/home/ae/Documents/clDNN/src/include/fully_connected_inst.h:50:28: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
     const bool bias_term() const { return !argument.bias.empty(); }
                            ^
cc1plus: all warnings being treated as errors
src/CMakeFiles/clDNN_shlib.dir/build.make:498: recipe for target 'src/CMakeFiles/clDNN_shlib.dir/fully_connected.cpp.o' failed
make[2]: *** [src/CMakeFiles/clDNN_shlib.dir/fully_connected.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/clDNN_shlib.dir/all' failed
make[1]: *** [src/CMakeFiles/clDNN_shlib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
ae@hped800nuc2:~/Documents/clDNN/build$ cmake --version
cmake version 3.8.0

**Comment by tponieck** [comment]
Hi Mrsabhar
Thank you for your input. Fix for that has been pushed with 
SHA-1: 96b93d1a6d9fd5e46b056e8ad09a0fd19844daa1

Thanks
Tomek
