### ISSUE TITLE
Profiling Event in Tutorial Chapter 5 returns 0 nanosecond

### ISSUE THREAD

**Issue by Darwin2011** [01org/clDNN#11]
Hello,

I run the Chapter 5 in tutorial and get each kernel's timing. But the timing should be not correct.
> fc:
>         submission:0nanoseconds
>         starting:0nanoseconds
>         executing:0nanoseconds
> fc_bias:
>         submission:0nanoseconds
>         starting:0nanoseconds
>         executing:0nanoseconds
> fc_weights:
>         submission:0nanoseconds
>         starting:0nanoseconds
>         executing:0nanoseconds
> input:
>         submission:0nanoseconds
>         starting:0nanoseconds
>         executing:0nanoseconds
> relu:
>         submission:0nanoseconds
>         starting:0nanoseconds
>         executing:0nanoseconds
> softmax:
>         submission:0nanoseconds
>         starting:0nanoseconds
>         executing:0nanoseconds
> 

My environment is Ubuntu 14.04 with Beignet driver.
The device information is as the following.

> Number of platforms:                             1
>   Platform Profile:                              FULL_PROFILE
>   Platform Version:                              OpenCL 1.2 beignet 1.3 (git-8bd8c3a)
>   Platform Name:                                 Intel Gen OCL Driver
>   Platform Vendor:                               Intel
>   Platform Extensions:                           cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
> 
> 
>   Platform Name:                                 Intel Gen OCL Driver
> Number of devices:                               1
>   Device Type:                                   CL_DEVICE_TYPE_GPU
>   Device ID:                                     32902
>   Max compute units:                             72
>   Max work items dimensions:                     3
>     Max work items[0]:                           512
>     Max work items[1]:                           512
>     Max work items[2]:                           512
>   Max work group size:                           512
>   Preferred vector width char:                   16
>   Preferred vector width short:                  8
>   Preferred vector width int:                    4
>   Preferred vector width long:                   2
>   Preferred vector width float:                  4
>   Preferred vector width double:                 0
>   Native vector width char:                      8
>   Native vector width short:                     8
>   Native vector width int:                       4
>   Native vector width long:                      2
>   Native vector width float:                     4
>   Native vector width double:                    2
>   Max clock frequency:                           1000Mhz
>   Address bits:                                  32
>   Max memory allocation:                         3221225472
>   Image support:                                 Yes
>   Max number of images read arguments:           128
>   Max number of images write arguments:          8
>   Max image 2D width:                            8192
>   Max image 2D height:                           8192
>   Max image 3D width:                            8192
>   Max image 3D height:                           8192
>   Max image 3D depth:                            2048
>   Max samplers within kernel:                    16
>   Max size of kernel argument:                   1024
>   Alignment (bits) of base address:              1024
>   Minimum alignment (bytes) for any datatype:    128
>   Single precision floating point capability
>     Denorms:                                     No
>     Quiet NaNs:                                  Yes
>     Round to nearest even:                       Yes
>     Round to zero:                               No
>     Round to +ve and infinity:                   No
>     IEEE754-2008 fused multiply-add:             No
>   Cache type:                                    Read/Write
>   Cache line size:                               64
>   Cache size:                                    8192
>   Global memory size:                            4294967296
>   Constant buffer size:                          134217728
>   Max number of constant args:                   8
>   Local memory type:                             Local
>   Local memory size:                             65536
>   Error correction support:                      0
>   Unified memory for Host and Device:            1
>   Profiling timer resolution:                    80
>   Device endianess:                              Little
>   Available:                                     Yes
>   Compiler available:                            Yes
>   Execution capabilities:
>     Execute OpenCL kernels:                      Yes
>     Execute native function:                     Yes
>   Queue properties:
>     Out-of-Order:                                No
>     Profiling :                                  Yes
>   Platform ID:                                   0x7fc8d642ebe0
>   Name:                                          Intel(R) HD Graphics Skylake Server GT4
>   Vendor:                                        Intel
>   Device OpenCL C version:                       OpenCL C 1.2 beignet 1.3 (git-8bd8c3a)
>   Driver version:                                1.3
>   Profile:                                       FULL_PROFILE
>   Version:                                       OpenCL 1.2 beignet 1.3 (git-8bd8c3a)
>   Extensions:                                    cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_fp16

Could you identify the issue and give me some suggestions?

Best Regards

**Comment by ddominia** [comment]
Hello Darwin2011,
We are checking it now.
Thanks for pointing out.

Thanks,
Dawid

**Comment by sareluzi** [comment]
Should be fixed in next week's drop.

**Comment by tponieck** [comment]
Fixed with drop 4
