### ISSUE TITLE
Enable the DL community to innovate on many integrated core coprocessors. 

### ISSUE THREAD

**Issue by mancoast** [01org/clDNN#12]
Greetings Developers,

Does there exist plans to optimize for Xeon Phi Coprocessors?
Is it possible to execute and test using MIC hardware?

Thanks,
Coast

**Comment by tponieck** [comment]
Hi Coast,
for CPU Core, Xeon, Xeon Phi, Intel offers MKL-DNN solution:
https://github.com/01org/mkl-dnn 
regards,
tponieck

**Comment by mancoast** [comment]
Thanks! That's what I seek.
