### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by covteam** [01org/clDNN#13]
It seems like the "System Requirements" on the main github page is a bit misleading. It says that clDNN supports Intel® HD Graphics and Intel® Iris® Graphics and is optimized for Skylake and Apollolake, when in fact it does not support anything older than gen 5.

The following exception is thrown when attempting to create an engine on an i7-4712HQ:
Device lookup failed - unsupported device id: 0x416. Note: HD5xx+ devices are supported

Are there any plans to support HD4 and older ?

**Comment by sareluzi** [comment]
Hi CovTeam,

Thank you for your comment. You are correct; we will update the system-requirements section accordingly.
clDNN is tested on the systems mentioned in that section. Specifically we haven't tested on the device that you mentioned, and we are currently not planning to.
