### ISSUE TITLE
size_offset_stride_padding.html

### ISSUE THREAD

**Issue by covteam** [01org/clDNN#14]
The detailed description of the convolution class refers to a html file that seem to be missing.

"Look into docs/size_offset_stride_padding.html for description how size, offsets, stride & padding parameters work."

**Comment by sareluzi** [comment]
Hi covteam,

You are right. We are checking it now.
Thanks for pointing out.


Thanks,

Uzi

**Comment by tponieck** [comment]
Fixed with drop #4
