### ISSUE TITLE
[Question] If I have googlenet.prototxt, how can I convert to clDNN?

### ISSUE THREAD

**Issue by yinquan529** [01org/clDNN#17]
If I have googlenet.prototxt, how can I convert to clDNN?

Thanks a lot.

**Comment by ddominia** [comment]
For such activity you would need to download Deployment Toolkit, which is delivered with Intel Computer Vision SDK:
https://software.intel.com/en-us/computer-vision-sdk

Instruction how to use it can be found here:
https://software.intel.com/en-us/dl-deployment-tool-devguide
