### ISSUE TITLE
Disclaimer in README.md

### ISSUE THREAD

**Issue by domibel** [01org/clDNN#2]
Could you please comment on the following in README.md
"
You may not use or facilitate the use of this document in connection with any infringement or other legal analysis concerning Intel products described herein. You agree to grant Intel® a non-exclusive, royalty-free license to any patent claim thereafter drafted which includes subject matter disclosed herein.
"
Is this part of the license? Could you please add a license file to the top level directory which covers everything in the repository?

**Comment by ddominia** [comment]
We are licensed under Apache License 2.0 
http://www.apache.org/licenses/LICENSE-2.0

Disclaimer had been removed
