### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by chungyeh** [01org/clDNN#3]
Build fail log are below. Solved by adding **#include "cmath" in src/gpu/kernel.h** 

[patch]
diff --git a/src/gpu/kernel.h b/src/gpu/kernel.h
index 5a89e4e..b6ce0a5 100644
--- a/src/gpu/kernel.h
+++ b/src/gpu/kernel.h
@@ -25,6 +25,7 @@
 
 #include <iostream>
 #include <sstream>
+#include <cmath>
 
 namespace neural { namespace gpu {
 

[log]
[  1%] Building CXX object src/CMakeFiles/clDNN_shlib.dir/network.cpp.o
In file included from /home/cv/cldnn/src/network.cpp:29:0:
/home/cv/cldnn/src/gpu/kernel.h: In function ‘std::string neural::gpu::to_code_string(T) [with T = float; std::string = std::basic_string<char>]’:
/home/cv/cldnn/src/gpu/kernel.h:69:9: error: ‘isinf’ is not a member of ‘std’
     if (std::isinf(val))
         ^
/home/cv/cldnn/src/gpu/kernel.h:70:61: error: ‘signbit’ is not a member of ‘std’
         std::snprintf(buffer, sizeof(buffer), "%sINFINITY", std::signbit(val) ? "-" : "");
                                                             ^
/home/cv/cldnn/src/gpu/kernel.h: In function ‘std::string neural::gpu::to_code_string(T) [with T = double; std::string = std::basic_string<char>]’:
/home/cv/cldnn/src/gpu/kernel.h:80:9: error: ‘isinf’ is not a member of ‘std’
     if (std::isinf(val))
         ^
/home/cv/cldnn/src/gpu/kernel.h:81:61: error: ‘signbit’ is not a member of ‘std’
         std::snprintf(buffer, sizeof(buffer), "%sINFINITY", std::signbit(val) ? "-" : "");
                                                             ^
make[2]: *** [src/CMakeFiles/clDNN_shlib.dir/network.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/clDNN_shlib.dir/all] Error 2
make: *** [all] Error 2

**Comment by mwalkowi** [comment]
Hi chungyeh,
Thank you for filling the issue. Fix has been committed to master (SHA: https://github.com/01org/clDNN/commit/c84e0f00cf16822ae8052cd086a2d21bb5324329).

Best Wishes
Marcin W.
