### ISSUE TITLE
macOS build fail

### ISSUE THREAD

**Issue by toddlt** [01org/clDNN#4]
I try to compile on macOS. I have installed boost by package manager Homebrew, but Cmake can't find boost. Here is error message:

```
  Could not find the following static Boost libraries:

          boost_system
          boost_date_time
          boost_program_options
          boost_filesystem

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:577 (find_package)
```

```
CMake Error at CMakeCompilerLinkerOpts.txt:328 (message):
  [clDNN] Unknown compiler.  Please define support for it or use different
  compiler.
Call Stack (most recent call first):
  CMakeLists.txt:709 (include)
```

**Comment by ddominia** [comment]
We are supporting Linux and Windows only.

Our software was validated on:
CentOS* 7 with GNU* Compiler Collection 5.2 (64-bit only)
Windows® 10 and Windows® Server 2012 R2 with MSVC 14.0

**Comment by dendisuhubdy** [comment]
Got the same error issue @toddlt. Has it been validated on Debian?

**Comment by toddlt** [comment]
I have compiled it on Ubuntu16.04, so I think it should work well on Debian. @dendisuhubdy
