### ISSUE TITLE
Example of DQN and ALE

### ISSUE THREAD

**Issue by viper7882** [01org/clDNN#5]
Hi guys,

Thank you for the great work to bring Intel GPU into DNN. I applauded this move to level up OpenCL into more DNN applications.

I'm looking for Deep Q-Network (DQN and Double DQN)  where user could connect and link to Atari Learning Environment (ALE) in clDNN but couldn't find any similar example. By any chance if it is not available, would you consider to add this example in as ALE is a critical application in my DNN research and I would like to run DNN in Intel GPUs.

**Comment by tponieck** [comment]
Hi,
DQN's and reinforcement learning are topics that we have on our  roadmap. We are targeting to support both features by the end of this year (2017).

regards.

**Comment by viper7882** [comment]
I'm glad to hear that. Looking forward to hear your announcement for DQN and reinforcement learning by end of 2017y.
