### ISSUE TITLE
a few lines in convolution.cpp are formatted with tabs, which triggers the error 'misleading-indentation' in gcc

### ISSUE THREAD

**Issue by fventuri** [01org/clDNN#6]
A few lines (38, 47, and a few others) in the source file 'convolution.cpp' are formatted using the tab character (with a tab length of 4). If they are viewed with a tab length of 8 they look incorrectly indented and trigger errors like this one in gcc:

`/home/franco/cldnn/src/convolution.cpp:44:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (kernel_xy.size() != 2)
`

Replacing all the tabs with 4 spaces (with something like s/\t/    /g) fixes the problem and the code compiles successfully.

**Comment by tponieck** [comment]
fixed with drop 3.0
