### ISSUE TITLE
many disabled tests

### ISSUE THREAD

**Issue by domibel** [01org/clDNN#8]
I am using the following variables to enable some tests:
 -DCLDNN__RUN_TESTS:BOOL=ON    -DCLDNN__INCLUDE_TESTS:BOOL=ON

About 125 tests pass, but there is a warning that more than 1000 tests have been disabled. What is the reason?

**Comment by tponieck** [comment]
Just time saving. Running whole test scope takes too long for CI, or even weekly testing.
