### ISSUE TITLE
Image name variables are not be used correctly

### ISSUE THREAD

**Issue by gwtnb** [01org/clDNN#9]
The variable [`img_name`](https://github.com/01org/clDNN/blob/6f5c9f231ae720c106670a153ab60469d5a6ff2f/tests/examples/example_cldnn.cpp#L213) is [not used correctly](https://github.com/01org/clDNN/blob/6f5c9f231ae720c106670a153ab60469d5a6ff2f/tests/examples/example_cldnn.cpp#L216) but always `"one.jpg"` is used. There is the same problem in https://github.com/01org/clDNN/blob/6f5c9f231ae720c106670a153ab60469d5a6ff2f/tutorial/example_cldnn.cpp#L213.

**Comment by tponieck** [comment]
fixed, thanks for feedback
